from __future__ import annotations

from typing import Protocol

from app.voice.models import Transcript, VoiceAvailability


class Microphone(Protocol):
    def availability(self) -> VoiceAvailability: ...
    def record(self, seconds: float) -> object: ...
    def cancel(self) -> None: ...


class SpeechRecognizer(Protocol):
    def availability(self) -> VoiceAvailability: ...
    def transcribe(self, audio: object) -> Transcript: ...


class SpeechSynthesizer(Protocol):
    def availability(self) -> VoiceAvailability: ...
    def speak(self, text: str) -> None: ...
    def cancel(self) -> None: ...
