import { AtSign, CheckCircle2, Clock3, MessageCircle, Phone } from "lucide-react"
import type { OutreachActivity } from "@/lib/api/sales"

const statusLabels = { opened: "Canal aberto", sent: "Envio confirmado", replied: "Resposta registrada", no_response: "Sem resposta" }
const channelLabels = { whatsapp: "WhatsApp", instagram: "Instagram", phone: "Telefone" }

export function LeadActivityTimeline({ activities = [] }: { activities?: OutreachActivity[] }) {
  return <section className="border-t pt-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Histórico de relacionamento</h2><p className="mt-1 text-xs text-muted-foreground">Ações confirmadas e próximos acompanhamentos.</p></div><span className="rounded-md border px-2 py-1 text-xs tabular-nums">{activities.length}</span></div>
    {!activities.length ? <p className="mt-4 rounded-xl border border-dashed p-5 text-sm text-muted-foreground">Nenhuma abordagem registrada para este lead.</p> : <ol className="mt-4 space-y-3">{activities.map((activity) => <li key={activity.id} className="flex gap-3 rounded-xl border bg-muted/25 p-4"><div className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-full bg-background shadow-sm">{activity.channel === "whatsapp" ? <MessageCircle className="size-4" /> : activity.channel === "instagram" ? <AtSign className="size-4" /> : <Phone className="size-4" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-medium">{statusLabels[activity.status]} · {channelLabels[activity.channel]}</p><time className="text-xs text-muted-foreground">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(activity.created_at))}</time></div>{activity.body ? <p className="mt-2 line-clamp-3 whitespace-pre-wrap text-xs leading-5 text-muted-foreground">{activity.body}</p> : null}{activity.next_follow_up_at ? <p className="mt-2 flex items-center gap-1.5 text-xs font-medium text-primary"><Clock3 className="size-3.5" />Follow-up em {new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(activity.next_follow_up_at))}</p> : activity.status === "sent" ? <p className="mt-2 flex items-center gap-1.5 text-xs text-emerald-600"><CheckCircle2 className="size-3.5" />Aguardando resposta</p> : null}</div></li>)}</ol>}
  </section>
}
