"use client"
import { useState } from "react"
import { Check, ShieldCheck } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
export function SettingsForm(){const [saved,setSaved]=useState(false);return <div className="grid gap-5 xl:grid-cols-[1.3fr_1fr]"><Card><CardHeader><CardTitle>Operação e oferta</CardTitle></CardHeader><CardContent><form className="space-y-5" onSubmit={e=>{e.preventDefault();setSaved(true)}}><div className="grid gap-2"><Label htmlFor="business">Nome do negócio</Label><Input id="business" defaultValue="Studio Aurora"/></div><div className="grid gap-2"><Label htmlFor="offer">Oferta principal</Label><Textarea id="offer" defaultValue="Consultoria de interiores para apartamentos urbanos"/></div><div className="grid gap-2"><Label htmlFor="tone">Tom de atendimento</Label><Input id="tone" defaultValue="Consultivo, acolhedor e objetivo"/></div><div className="flex items-center justify-between gap-3"><p className="text-xs text-muted-foreground" role="status">{saved&&"Alterações demonstrativas salvas localmente."}</p><Button type="submit">{saved&&<Check/>}Salvar</Button></div></form></CardContent></Card><Card><CardHeader><CardTitle>Autonomia e aprovação</CardTitle></CardHeader><CardContent><p className="text-sm font-medium">Nível 3 · prepara e pede aprovação</p><p className="mt-2 text-xs leading-5 text-muted-foreground">A Kiara não executa ações externas sem aprovação humana registrada.</p><div className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-500/[0.08] p-3 text-sm"><ShieldCheck className="size-4 text-emerald-600"/>Kill switch disponível</div></CardContent></Card></div>}
