import Link from "next/link"
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, FileQuestion, Lightbulb, MessageCircle, ShieldCheck, Sparkles } from "lucide-react"
import { notFound } from "next/navigation"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { demoLeads } from "@/lib/mock-data"

const details: Record<string,{summary:string;evidence:string[];hypotheses:string[];gaps:string[]}> = {
  "ana-costa": { summary:"Busca consultoria de interiores para um apartamento de 68 m² em São Paulo, com intenção de começar neste semestre.", evidence:["Apartamento de 68 m² · DM inbound, hoje 14:22","Localização: São Paulo · DM inbound, hoje 14:22","Início pretendido neste semestre · DM inbound, hoje 14:22"], hypotheses:["Pode valorizar soluções para espaços compactos","Atendimento remoto ainda não confirmado"], gaps:["Faixa de investimento não informada","Ambientes prioritários pendentes"] },
  "marina-lima": { summary:"Está avaliando um projeto residencial e já informou metragem e cidade. O próximo passo é confirmar escopo e prioridade.", evidence:["Apartamento de 82 m² · DM inbound","Localização: Campinas · DM inbound"], hypotheses:["Pode precisar de execução em etapas"], gaps:["Ambientes prioritários","Faixa de investimento"] },
  "lucas-rocha": { summary:"Pediu um orçamento inicial e demonstrou preocupação com prazo. A qualificação ainda não está completa.", evidence:["Pedido de orçamento · DM inbound","Pergunta sobre prazo curto · DM inbound"], hypotheses:["Urgência pode influenciar o escopo"], gaps:["Data limite","Metragem e localização"] },
  "bia-martins": { summary:"Chegou por conteúdo público e iniciou uma conversa sobre reforma residencial. O contexto ainda precisa de revisão.", evidence:["Origem em conteúdo do Instagram · DM inbound"], hypotheses:["Interesse em reforma residencial"], gaps:["Imóvel, localização e prazo","Faixa de investimento"] },
  "rafa-souza": { summary:"Oportunidade comercial em etapa de proposta. O follow-up precisa preservar o histórico e a aprovação humana.", evidence:["Projeto comercial · registro demonstrativo","Proposta preparada · pipeline demonstrativo"], hypotheses:["Decisão pode envolver mais pessoas"], gaps:["Data de decisão confirmada"] },
}

export default async function LeadPage({params}:{params:Promise<{leadId:string}>}) {
  const {leadId}=await params
  const lead=demoLeads.find((item)=>item.id===leadId)
  if(!lead) notFound()
  const info=details[lead.id]

  return <div className="space-y-5">
    <Link href="/app/pipeline" className="inline-flex min-h-11 items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft aria-hidden="true" className="size-4" />Voltar ao Pipeline</Link>
    <header className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="h-1 bg-primary" /><div className="flex flex-col gap-5 p-5 sm:p-6 lg:flex-row lg:items-center"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-primary/10 text-sm font-semibold text-primary">{lead.name.split(" ").map((part)=>part[0]).join("")}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">{lead.name}</h1><Badge>{lead.stage}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{lead.handle} · Instagram inbound · dados fictícios</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs"><span><strong className="font-mono tabular-nums">{lead.score}/100</strong> sinal demo · confiança {lead.confidence.toLowerCase()}</span><span>Responsável: <strong>{lead.owner}</strong></span><span>Atualizado {lead.last}</span></div></div><div className="flex flex-wrap gap-2"><Badge variant="outline"><ShieldCheck aria-hidden="true" />Canal permitido</Badge><Badge variant="secondary">Sem envio automático</Badge></div></div></header>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(300px,0.65fr)]">
      <Card><Tabs defaultValue="summary"><CardHeader className="border-b pb-0"><TabsList variant="line" className="h-11 max-w-full overflow-x-auto"><TabsTrigger value="summary">Resumo</TabsTrigger><TabsTrigger value="qualification">Qualificação</TabsTrigger><TabsTrigger value="history">Histórico</TabsTrigger></TabsList></CardHeader><CardContent className="p-5 sm:p-6"><TabsContent value="summary" className="m-0"><p className="max-w-3xl text-sm leading-7 text-muted-foreground">{info.summary}</p><div className="mt-6 grid gap-6 md:grid-cols-2"><InfoSection icon={CheckCircle2} title="Confirmado" items={info.evidence} tone="text-emerald-600" /><InfoSection icon={Lightbulb} title="Inferido" items={info.hypotheses} tone="text-primary" /></div></TabsContent><TabsContent value="qualification" className="m-0"><InfoSection icon={FileQuestion} title="Falta saber" items={info.gaps} tone="text-amber-600" /><p className="mt-5 rounded-xl bg-muted/45 p-4 text-xs leading-5 text-muted-foreground">O score demonstrativo organiza a fila; ele não substitui a evidência nem autoriza uma ação externa.</p></TabsContent><TabsContent value="history" className="m-0"><SignalTrail /></TabsContent></CardContent></Tabs></Card>

      <aside className="xl:sticky xl:top-24 xl:self-start"><Card className="border-primary/25"><CardHeader><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-primary">Próxima decisão</p><CardTitle>{lead.next}</CardTitle></CardHeader><CardContent><div className="space-y-3 border-y py-4 text-sm"><p className="flex items-center justify-between gap-3"><span className="text-muted-foreground">Prazo</span><strong className="font-mono text-xs">{lead.due}</strong></p><p className="flex items-center justify-between gap-3"><span className="text-muted-foreground">Responsável</span><strong>{lead.owner}</strong></p><p className="flex items-start justify-between gap-3"><span className="text-muted-foreground">Lacuna crítica</span><strong className="max-w-44 text-right">{info.gaps[0]}</strong></p></div><Button asChild className="mt-5 w-full"><Link href="/app/inbox">Abrir conversa <ArrowRight aria-hidden="true" /></Link></Button><p className="mt-3 text-xs leading-5 text-muted-foreground">A resposta poderá ser preparada na Inbox, mas continuará exigindo revisão humana antes de qualquer envio.</p></CardContent></Card></aside>
    </div>
  </div>
}

function InfoSection({icon:Icon,title,items,tone}:{icon:typeof CheckCircle2;title:string;items:string[];tone:string}) { return <section><h2 className="flex items-center gap-2 text-sm font-semibold"><Icon aria-hidden="true" className={`size-4 ${tone}`} />{title}<Badge variant="outline" className="font-mono">{items.length}</Badge></h2><ul className="mt-3 divide-y border-y">{items.map((item)=><li key={item} className="py-3 text-sm leading-6 text-muted-foreground">{item}</li>)}</ul></section> }
function SignalTrail() { const items=["DM inbound recebida","Intenção analisada pela Kiara","Qualificação revisada por uma pessoa"]; return <ol className="space-y-0">{items.map((item,index)=><li key={item} className="relative flex gap-4 pb-6 last:pb-0"><span aria-hidden="true" className="relative z-10 grid size-7 shrink-0 place-items-center rounded-full border bg-card text-primary">{index===0?<MessageCircle className="size-3.5" />:index===1?<Sparkles className="size-3.5" />:<Clock3 className="size-3.5" />}</span>{index<items.length-1&&<span aria-hidden="true" className="absolute bottom-0 left-3.5 top-7 w-px bg-border" />}<div><p className="text-sm font-medium">{item}</p><p className="mt-1 text-xs text-muted-foreground">Evento demonstrativo · sem confirmação externa</p></div></li>)}</ol> }
